name: manual_build

on:
  push:
    branches:
      - master

jobs:
  manual_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: "Install packages"
      - run: pip install -r requirements.txt
      - name: "Build image"
        run: python main.py